USE acaipde ;

INSERT INTO bairro(nome) VALUE ('Águas Lindas');
INSERT INTO bairro(nome) VALUE ('Aurá');
INSERT INTO bairro(nome) VALUE ('Barreiro');
INSERT INTO bairro(nome) VALUE ('Batista Campos');
INSERT INTO bairro(nome) VALUE ('Cabanagem');
INSERT INTO bairro(nome) VALUE ('Canudos');
INSERT INTO bairro(nome) VALUE ('Castanheira');
INSERT INTO bairro(nome) VALUE ('Ciadade Velha');
INSERT INTO bairro(nome) VALUE ('Condor');
INSERT INTO bairro(nome) VALUE ('Coqueiro');
INSERT INTO bairro(nome) VALUE ('Cremação');
INSERT INTO bairro(nome) VALUE ('Curió-Utinga');
INSERT INTO bairro(nome) VALUE ('Fatima');
INSERT INTO bairro(nome) VALUE ('Guamá');
INSERT INTO bairro(nome) VALUE ('Guanabara');
INSERT INTO bairro(nome) VALUE ('Icoaraci');
INSERT INTO bairro(nome) VALUE ('Ilha de Cintra');
INSERT INTO bairro(nome) VALUE ('Ilha de Cotijuba');
INSERT INTO bairro(nome) VALUE ('Ilha do Combú');
INSERT INTO bairro(nome) VALUE ('Ilha do Fortinho');
INSERT INTO bairro(nome) VALUE ('Ilha do Jutuba');
INSERT INTO bairro(nome) VALUE ('Ilha do Murucutu');
INSERT INTO bairro(nome) VALUE ('Ilha dos Patos');
INSERT INTO bairro(nome) VALUE ('Ilha Grande');
INSERT INTO bairro(nome) VALUE ('Ilha Negra');
INSERT INTO bairro(nome) VALUE ('Jurunas');
INSERT INTO bairro(nome) VALUE ('Mangueirão');
INSERT INTO bairro(nome) VALUE ('Marambaia');
INSERT INTO bairro(nome) VALUE ('Marancagalha');
INSERT INTO bairro(nome) VALUE ('Marco');
INSERT INTO bairro(nome) VALUE ('Montese');
INSERT INTO bairro(nome) VALUE ('Mosqueiro');
INSERT INTO bairro(nome) VALUE ('Nazaré');
INSERT INTO bairro(nome) VALUE ('Outeiro');
INSERT INTO bairro(nome) VALUE ('Parque Guajará');
INSERT INTO bairro(nome) VALUE ('Parque Verde');
INSERT INTO bairro(nome) VALUE ('Pedreira');
INSERT INTO bairro(nome) VALUE ('Pratinha');
INSERT INTO bairro(nome) VALUE ('Reduto');
INSERT INTO bairro(nome) VALUE ('Sacramenta');
INSERT INTO bairro(nome) VALUE ('São Brás');
INSERT INTO bairro(nome) VALUE ('Souza');
INSERT INTO bairro(nome) VALUE ('Tapanã');
INSERT INTO bairro(nome) VALUE ('Telegrafo');
INSERT INTO bairro(nome) VALUE ('Tenoné');
INSERT INTO bairro(nome) VALUE ('Umarizal');
INSERT INTO bairro(nome) VALUE ('Una');
INSERT INTO bairro(nome) VALUE ('Val-de-Cães');